const {test}=require('node:test'); const assert=require('node:assert/strict');const {inspect}=require('../scripts/tradcoin-preflight.cjs');
const fixture=()=>({state:'approval_required',operating_mode:'L0_co_writer_approval_only',publishing_enabled:false,external_actions_attempted:false,tradcoin:{exact_service:null,chain:null,ticker:null,contract_or_mint:null,official_url:null,legal_owner_entity_and_jurisdiction:null,creator_allocation:null,treasury_holdings_and_control:null,creator_fees_or_compensation:null,owner_material_relationship:null,direct_purchase_cta:'blocked',token_link:'blocked',paid_promotion:'blocked_pending_platform_and_legal_review'},starter_assets:[{name:'draft',approval_state:'awaiting_owner_approval',queue_state:'not_queued',schedule_state:'not_scheduled',provider_id:null}]});
test('unknown chain and economic relationships block review readiness',()=>{const r=inspect(fixture());assert.equal(r.ready,false);assert.ok(r.blockers.includes('unresolved: chain'));assert.ok(r.blockers.includes('unresolved: owner_material_relationship'));});
test('publishing flag cannot silently become enabled',()=>{const m=fixture();m.publishing_enabled=true;assert.ok(inspect(m).blockers.includes('publishing must remain disabled'));});
test('queued or provider-bound assets violate draft boundary',()=>{const m=fixture();m.starter_assets[0].provider_id='simulated';assert.ok(inspect(m).blockers.some(x=>x.startsWith('asset execution boundary violated')));});
test('missing manifest fails closed',()=>assert.equal(inspect(null).ready,false));
test('zero allocation or compensation is not treated as missing',()=>{const m=fixture();m.tradcoin.creator_allocation=0;m.tradcoin.creator_fees_or_compensation=0;assert.ok(!inspect(m).blockers.includes('unresolved: creator_allocation'));assert.ok(!inspect(m).blockers.includes('unresolved: creator_fees_or_compensation'));});
test('populated evidence never changes offline execution',()=>{const m=fixture();for(const k of Object.keys(m.tradcoin))if(m.tradcoin[k]===null)m.tradcoin[k]='simulation-only fixture';const r=inspect(m);assert.equal(r.ready,true);assert.equal(r.execution,'offline_review_only');});

